# Generated by Django 3.2 on 2023-09-26 14:02

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations

User = get_user_model()

def create_dev_superuser(*args, **kwargs):

    if settings.DEBUG:
        DEV_ADMIN = {"username": "admin", "password": "admin"}
        User.objects.create_superuser(**DEV_ADMIN)

class Migration(migrations.Migration):

    dependies = []

    operations = [migrations.RunPython(create_dev_superuser)]